version: "3.9"

services:
  processor:
    build: ./services/processor
    ports:
      - "5000:5000"
    tty: true
    stdin_open: true

  collector:
    build: ./services/collector
    ports:
      - "5001:5000"